---
- name: Install and configure Nginx as load balancer
  hosts: nginx
  tasks:
    - name: Change Hostname
      hostname:
        name: "{{ nginx_host_name  }}"
      become: true

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: yes

    - name: Copy configure
      copy:
        src: ../source/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
