---
- name: Install and configure Nginx as load balancer
  hosts: all
  become: yes
  roles:
    - common
    - { role: roles/nginx, when: "'nginx' in group_names" }
    - { role: roles/web, when: "'web' in group_names" }
